In [1]:
import json
import pandas as pd
import requests

top_rated = []
for i in range(1,1000):
    url = 'https://api.themoviedb.org/3/movie/top_rated?api_key={1}&language=ko-KR&page={0}'.format(i,'36927ad1d2817ff0fa31947e47d186fd')
    resp = requests.get(url)
    top_rated.append(json.loads(resp.content))

    if i == 10:
        break

top_rated_movies = []
for row in top_rated:
    for result in row ['results']:
        top_rated_movies.append(result)

In [2]:
top_rated_movies=pd.DataFrame(top_rated_movies)
top_rated_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              200 non-null    bool
 1   backdrop_path      199 non-null    object
 2   genre_ids          200 non-null    object
 3   id                 200 non-null    int64
 4   original_language  200 non-null    object
 5   original_title     200 non-null    object
 6   overview           200 non-null    object
 7   popularity         200 non-null    float64
 8   poster_path        200 non-null    object
 9   release_date       200 non-null    object
 10  title              200 non-null    object
 11  video              200 non-null    bool
 12  vote_average       200 non-null    float64
 13  vote_count         200 non-null    int64
dtypes: bool(2), float64(2), int64(2), object(8)
memory usage: 19.3+ KB

In [3]:
top_rated_movies.to_csv("../data-files/top_rated_movies.csv", header=True, index=True)

In [3]:
top_rated_movies=top_rated_movies.drop(['adult', 'backdrop_path', 'video', 'genre_ids'], axis=1)

In [4]:
top_rated_movies.head(2)

,id,original_language,original_title,overview,popularity,poster_path,release_date,title,vote_average,vote_count
0,19404,hi,दिलवाले दुल्हनिया ले जायेंगे,영국에서 유학중인 라즈(샤룩 칸)와 인도 처녀 심란(까졸). 심란은 부모님이 정해...,21.244,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,용감한 자가 신부를 데려가리,8.7,3265
1,278,en,The Shawshank Redemption,촉망받는 은행 간부 앤디 듀프레인은 아내와 그녀의 정부를 살해했다는 누명을 쓴다. ...,54.750,/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg,1994-09-23,쇼생크 탈출,8.7,20242

In [5]:
# 칼럼이름을 DB 칼럼이름과 동일하게 변경

top_rated_movies=top_rated_movies.rename(columns={'id':'movie_id', 'original_title':'subtitle','poster_path':'posterpath'})
top_rated_movies.head(25)

,movie_id,original_language,subtitle,overview,popularity,posterpath,release_date,title,vote_average,vote_count
0,19404,hi,दिलवाले दुल्हनिया ले जायेंगे,영국에서 유학중인 라즈(샤룩 칸)와 인도 처녀 심란(까졸). 심란은 부모님이 정해...,21.244,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,용감한 자가 신부를 데려가리,8.7,3265
1,278,en,The Shawshank Redemption,촉망받는 은행 간부 앤디 듀프레인은 아내와 그녀의 정부를 살해했다는 누명을 쓴다. ...,54.750,/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg,1994-09-23,쇼생크 탈출,8.7,20242
2,238,en,The Godfather,"시실리에서 이민온 뒤, 정치권까지 영향력을 미치는 거물로 자리잡은 돈 꼴레오네는 갖...",53.394,/cOwVs8eYA4G9ZQs7hIRSoiZr46Q.jpg,1972-03-14,대부,8.7,15148
3,724089,en,Gabriel's Inferno Part II,,12.236,/8Rxutea68d940kg44Box5gFmKcF.jpg,2020-07-31,가브리엘의 지옥 파트 2,8.7,1345
4,482321,en,Ron's Gone Wrong,최첨단 소셜 AI 로봇 비봇이 모든 아이들의 친구가 되는 세상. 비봇을 갖는 것이 ...,1586.551,/o54XbhGUHeqDXr1Ro6GEGbodIuS.jpg,2021-10-15,고장난 론,8.6,253
5,761053,en,Gabriel's Inferno Part III,,30.110,/qtX2Fg9MTmrbgN1UUvGoCsImTM8.jpg,2020-11-19,Gabriel's Inferno Part III,8.6,908
6,424,en,Schindler's List,2차 세계대전 당시 독일군이 점령한 폴란드. 시류에 맞춰 자신의 성공을 추구하는 기...,37.200,/oyyUcGwLX7LTFS1pQbLrQpyzIyt.jpg,1993-11-30,쉰들러 리스트,8.6,12098
7,696374,en,Gabriel's Inferno,,11.496,/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg,2020-05-29,가브리엘의 지옥,8.6,2165
8,240,en,The Godfather: Part II,"아버지의 장례식 도중에 맏아들 파올로가 총에 맞아 죽고, 비토(로버트 드니로)는 겨...",39.191,/cj9UsJEN5bNf6ZoF1BbKjKN81hc.jpg,1974-12-20,대부 2,8.6,9121
9,255709,ko,소원,"어느 비 오는 아침, 학교를 가던 9살 소녀 소원은 술에 취한 아저씨에게 끌려가 믿...",9.157,/PZlNvDwKwHeHUsXnd6SEDXWZNn.jpg,2013-10-02,소원,8.6,236
10,372058,ja,君の名は。,시골에 사는 소녀 미츠하(가미시라이시 모네)는 어느 날 잠에서 깬 후 자신의 몸이 ...,143.927,/wx1Dxr4UyvN18SyC5GsVWWWtYja.jpg,2016-08-26,너의 이름은.,8.6,8112
11,283566,ja,シン・エヴァンゲリオン劇場版:||,에반게리온 신극장판의 제4탄이자 완결편. 미사토와 반네르프 조직 빌레는 코어와 닮은...,159.920,/eadcE25WY7XlnlhPnE9HuDWeLLj.jpg,2021-03-08,에반게리온 3.0+1.01,8.6,391
12,129,ja,千と千尋の神隠し,평범한 열 살 짜리 소녀 치히로 식구는 이사 가던 중 길을 잘못 들어 낡은 터널을 ...,65.395,/u1L4qxIu5sC2P082uMHYt7Ifvnj.jpg,2001-07-20,센과 치히로의 행방불명,8.5,12125
13,496243,ko,기생충,전원 백수로 살 길 막막하지만 사이는 좋은 기택 가족. 장남 기우에게 명문대생 친구...,73.015,/jjHccoFjbqlfr4VGLVLT7yek0Xn.jpg,2019-05-30,기생충,8.5,12618
14,632632,ja,映画 ギヴン,"고등학생 우에노야마 리츠카는 사토 마후유의 노랫소리에 충격을 받아 나카야마 하루키,...",118.594,/tVP1DjnljT1it6cAnn353cdVXDe.jpg,2020-08-22,기븐 극장판,8.5,273
15,389,en,12 Angry Men,"뉴욕시의 법정에 아버지를 칼로 찌른 한 소년의 살인혐의를 두고, 12인의 배심원들은...",24.413,/e02s4wmTAExkKg0yF4dEG98ZRpK.jpg,1957-04-10,12명의 성난 사람들,8.5,6002
16,644479,es,Dedicada a mi ex,,16.894,/xc4bTXVwYNXi10jG9dwcaYt5IpU.jpg,2019-11-01,Dedicada a mi ex,8.5,440
17,497,en,The Green Mile,미국 루이지애나의 콜드 마운틴 교도소. 폴은 사형수 감방의 간수장으로 일하고 있다....,39.398,/yuSpRhrTIJa5JN8oESrfD2bndp1.jpg,1999-12-10,그린 마일,8.5,13144
18,532067,ja,映画 この素晴らしい世界に祝福を！紅伝説,교통사고(!?)로 허무하게 인생의 막을 내릴 예정이었던 게임을 사랑하는 은둔형 외톨...,179.660,/hrE3lJtYnozIENA738mzQI65Avb.jpg,2019-08-30,이 멋진 세계에 축복을!,8.5,318
19,441130,en,Wolfwalkers,사냥꾼이 되고 싶은 소녀 로빈은 아버지와 함께 마지막 남겨진 늑대 떼를 없애기 위해...,24.000,/ehAKuE48okTuonq6TpsNQj8vFTC.jpg,2020-10-26,울프워커스,8.5,635
20,680,en,Pulp Fiction,펌프킨와 허니 버니가 레스토랑에서 강도 행각을 벌이기 시작한다. 빈센트와 그 동료 ...,48.679,/6lXRHGoEbnnBUKsuqpL9JxD4DzT.jpg,1994-09-10,펄프 픽션,8.5,22202
21,155,en,The Dark Knight,범죄와 부정부패를 제거하여 고담시를 지키려는 배트맨. 그는 짐 고든 형사와 패기 넘...,61.738,/f6dNinWX8rBM79JXKcShkfSh2oA.jpg,2008-07-14,다크 나이트,8.5,26326
22,122,en,The Lord of the Rings: The Return of the King,"사우론이 인간들의 마지막 요새인 곤도르를 향해 야욕을 드러내고 있는 한편, 아라곤은...",74.113,/tAXXuEAKLk2mOEIJzwajJQEnVZu.jpg,2003-12-01,반지의 제왕: 왕의 귀환,8.5,18675
23,13,en,Forrest Gump,"불편한 다리, 남들보다 조금 떨어지는 지능을 가진 포레스트 검프는 헌신적인 어머니의...",43.998,/xdJxoq0dtkchOkUz5UVKuxn7a2V.jpg,1994-07-06,포레스트 검프,8.5,21712
24,572154,ja,青春ブタ野郎はゆめみる少女の夢を見ない,"하늘과 바다가 반짝이는 마을 ""후지사와""에 사는 고등학생 아즈사가와 사쿠타는 같은 ...",171.418,/hqNkm15rQI6049Pg3XPSE8PMW98.jpg,2019-06-15,청춘 돼지는 꿈꾸는 소녀의 꿈을 꾸지 않는다,8.5,329

In [6]:
top_rated_movies.isna().sum()

movie_id             0
original_language    0
subtitle             0
overview             0
popularity           0
posterpath           0
release_date         0
title                0
vote_average         0
vote_count           0
dtype: int64

In [7]:
top_rated_movies_ids=top_rated_movies[["movie_id"]]
top_rated_movies_ids

     movie_id
0       19404
1         278
2         238
3      724089
4      482321
..        ...
195     42229
196    472454
197       489
198       655
199    455661

[200 rows x 1 columns]

In [14]:
import pymysql

conn = pymysql.connect(host="localhost",
                       database="finalteam3",
                       user="kdigital",
                       password="mysql",
                       charset="utf8")
cursor = conn.cursor()

# cursor.execute('DELETE FROM top_rated_movies')
error_list=[]
for movie_id in top_rated_movies_ids.values:
    # print(type(movie_id), movie_id)  # movie_id type이 nd.arrary임.
    try:
        sql= "INSERT INTO top_rated_movies VALUES(%s)"
        cursor.execute(sql, movie_id[0]) 
    except:
        error_list.append(movie_id)
    
conn.commit()
cursor.close()
conn.close()

In [15]:
len(error_list)

167

In [11]:
#없는 영화 업데이트

popular_movies = []
for i in error_list:
        for e in i:
                url="https://api.themoviedb.org/3/movie/{0}?api_key={1}&language=ko-KR".format(e,'36927ad1d2817ff0fa31947e47d186fd')
                response = requests.get(url)
                popular_movies.append(json.loads(response.content))

In [12]:
movies2 = pd.DataFrame(popular_movies)
movies2

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg,"{'id': 729322, 'name': 'Gabriel's Inferno Coll...",0,"[{'id': 10749, 'name': '로맨스'}]",https://watch.passionflix.com/watch/fc15dc25-c...,696374,tt11316854,en,Gabriel's Inferno,...,2020-05-29,0,122,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,가브리엘의 지옥,False,8.6,2165
1,False,/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg,None,11363000,"[{'id': 35, 'name': '코미디'}, {'id': 53, 'name':...",https://www.parasite-movie.com/,496243,tt6751668,ko,기생충,...,2019-05-30,257591776,131,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,행복은 나눌수록 커지잖아요,기생충,False,8.5,12617
2,False,/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg,None,0,"[{'id': 12, 'name': '모험'}, {'id': 35, 'name': ...",,40096,tt0271383,pt,O Auto da Compadecida,...,2000-09-15,4903192,104,"[{'english_name': 'Portuguese', 'iso_639_1': '...",Released,,어 독스 윌,False,8.5,832
3,False,/qknxyRgP6UTmwJ4B9tDAmzHMq7u.jpg,None,0,"[{'id': 10749, 'name': '로맨스'}, {'id': 16, 'nam...",,92321,tt2061702,ja,蛍火の杜へ,...,2011-09-17,0,45,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,,반딧불이의 숲으로,False,8.4,672
4,False,/88J6waYVTta8Qz3iX3qUeWNA5d5.jpg,None,0,"[{'id': 18, 'name': '드라마'}, {'id': 10749, 'nam...",,447362,tt6598238,en,Life in a Year,...,2020-11-27,0,107,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,우리의 마지막 1년,False,8.4,897
5,False,/pSsHFCwM5KMoRCc8X8wjpUDrlvr.jpg,None,0,"[{'id': 16, 'name': '애니메이션'}, {'id': 14, 'name...",http://sayoasa.jp,476292,tt7339826,ja,さよならの朝に約束の花をかざろう,...,2018-02-24,4300000,115,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,외톨이와 외톨이가 만났다!,이별의 아침에 약속의 꽃을 장식하자,False,8.4,400
6,False,/s3TBrRGB1iav7gFOCNx3H31MoES.jpg,None,160000000,"[{'id': 28, 'name': '액션'}, {'id': 878, 'name':...",http://inceptionmovie.warnerbros.com/,27205,tt1375666,en,Inception,...,2010-07-15,825532764,148,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,생각을 훔치는 거대한 전쟁,인셉션,False,8.4,30383
7,False,/oIQMt3Q6Qa37YD0JOdYkrIAPYDk.jpg,None,0,"[{'id': 18, 'name': '드라마'}, {'id': 10752, 'nam...",,25237,tt0091251,ru,Иди и смотри,...,1985-09-03,168817,142,"[{'english_name': 'Belarusian', 'iso_639_1': '...",Released,,컴 앤 씨,False,8.3,811
8,False,/2Kkqmy3EpXqBDqv1vvsNXX3pwww.jpg,None,0,"[{'id': 18, 'name': '드라마'}, {'id': 35, 'name':...",,42269,tt0075793,it,C'eravamo tanto amati,...,1974-12-21,0,124,"[{'english_name': 'Italian', 'iso_639_1': 'it'...",Released,,우리는 그토록 사랑했네,False,8.3,382
9,False,/78EAqp0sdvtaRryS9QtBQxiQBes.jpg,None,0,"[{'id': 16, 'name': '애니메이션'}, {'id': 18, 'name...",http://www.ookamikodomo.jp,110420,tt2140203,ja,おおかみこどもの雨と雪,...,2012-07-21,55060661,117,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,내가 사랑하게 된 사람은 늑대인간이었습니다,늑대아이,False,8.3,1656
10,False,/uUrV5KSjnZx47Dq7e6STr73iN4N.jpg,None,0,"[{'id': 18, 'name': '드라마'}, {'id': 35, 'name':...",,24188,tt0056512,it,Il sorpasso,...,1962-12-04,0,105,"[{'english_name': 'German', 'iso_639_1': 'de',...",Released,,이지 라이프,False,8.3,517
11,False,/bGksau9GGu0uJ8DJQ8DYc9JW5LM.jpg,None,13000000,"[{'id': 18, 'name': '드라마'}, {'id': 35, 'name':...",,77338,tt1675434,fr,Intouchables,...,2011-11-02,426588510,112,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,언터처블: 1%의 우정,False,8.3,14048
12,False,/d0IwJw1p2H0WYhk1iCwVNygpsUs.jpg,None,0,"[{'id': 18, 'name': '드라마'}]",,20532,tt0047445,ja,山椒大夫,...,1954-03-31,0,124,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,,산쇼다유,False,8.3,235
13,False,/txKj2q2bBUl7KqPkcSx19qB7Ylw.jpg,None,0,"[{'id': 18, 'name': '드라마'}, {'id': 53, 'name':...",,26451,tt0065889,it,Indagine su un cittadino al di sopra di ogni s...,...,1970-10-16,0,111,"[{'english_name': 'Italian', 'iso_639_1': 'it'...",Released,,완전 범죄,False,8.3,539
14,False,/7TZhRHh9fikzUVGbWCtdtxYOLxP.jpg,None,0,"[{'id': 80, 'name': '범죄'}, {'id': 18, 'name': ...",,29259,tt0054407,fr,Le Trou,...,1960-03-18,33187,132,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Released,,구멍,False,8.3,283
15,False,/evUB9YKE5IPPtQOchcEF6hS90BO.jpg,None,3000000,"[{'id': 18, 'name': '드라마'}, {'id': 9648, 'name...",,37257,tt0051201,en,Witness for the Prosecution,...,1957-12-17,9000000,116,"[{'english_name': 'German', 'iso_639_1': 'de',...",Released,,검찰 측 증인,False,8.2,907
16,False,/jEnh78WU2kxjCFaCdRh2r6ZDbfP.jpg,None,0,"[{'id': 28, 'name': '액션'}, {'id': 35, 'name': ...",http://www.ai-muki.com/,28422,tt1128075,ja,愛のむきだし,...,2009-01-31,0,237,"[{'english_name': 'Japanese', 'iso_639_1': 'ja...",Released,,러브 익스포져,False,8.2,291
17,False,/bg4B52loVIYZTf3odGQKVV6B55h.jpg,"{'id': 150954, 'name': 'Amici miei', 'poster_p...",0,"[{'id': 35, 'name': '코미디'}]",,20914,tt0072637,it,Amici miei,...,1975-10-24,0,140,"[{'english_name': 'Italian', 'iso_639_1': 'it'...",Released,,마이 프렌즈,False,8.2,543
18,False,/b7xQ5fuyVO4c24igizCfPgF6n7q.jpg,None,20000000,"[{'id': 18, 'name': '드라마'}, {'id': 10751, 'nam...",http://www.wonder.movie,406997,tt2543472,en,Wonder,...,2017-11-13,305937718,113,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"헬멧 속에 숨었던 아이, 세상 밖으로 나오다!",원더,False,8.2,6583
19,False,/wyvUmyzqGOBDyqLHRSukGDjI7bH.jpg,None,25000000,"[{'id': 18, 'name': '드라마'}]",,50014,tt1454029,en,The Help,...,2011-08-09,216639112,146,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,헬프,False,8.2,5930
20,False,/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg,None,55000000,"[{'id': 80, 'name': '범죄'}, {'id': 53, 'name': ...",http://www.jokermovie.net/,475557,tt7286456,en,Joker,...,2019-10-02,1074251311,122,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"내 인생이 비극인 줄 알았는데, 코미디였어",조커,False,8.2,19210
21,False,/2n1u392UAhtR4SvjCHC8BfLaamn.jpg,"{'id': 745388, 'name': 'Scenes From A Marriage...",150000,"[{'id': 18, 'name': '드라마'}, {'id': 10749, 'nam...",,133919,tt6725014,sv,Scener ur ett äktenskap,...,1974-09-15,0,169,"[{'english_name': 'Swedish', 'iso_639_1': 'sv'...",Released,,결혼의 풍경,False,8.2,223
22,False,/fcH7FM74GoHgOUnKjpGAoKOxWvY.jpg,None,0,"[{'id': 18, 'name': '드라마'}, {'id': 35, 'name':...",,55823,tt0052861,it,La grande guerra,...,1959-10-28,0,130,"[{'english_name': 'German', 'iso_639_1': 'de',...",Released,,La grande guerra,False,8.2,265
23,False,/x1ZNX6us2Y6H8nsLRvKuESQ772g.jpg,None,1100000,"[{'id': 27, 'name': '공포'}, {'id': 10402, 'name...",,92060,tt0088263,en,Michael Jackson's Thriller,...,1983-11-14,0,14,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,Michael Jackson's Thriller,False,8.2,401
24,False,/ryoWP1kvNcwPif6uNbuZwQfrJPy.jpg,"{'id': 656828, 'name': 'I soliti ignoti - coll...",0,"[{'id': 35, 'name': '코미디'}, {'id': 80, 'name':...",,24382,tt0052216,it,I soliti ignoti,...,1958-07-26,0,106,"[{'english_name': 'Italian', 'iso_639_1': 'it'...",Released,,마돈나 거리에서 한탕,False,8.2,518
25,False,/2W9of6vXs1yp6TEO5qoQZKTROw0.jpg,None,0,"[{'id': 10752, 'name': '전쟁'}, {'id': 18, 'name...",,426618,tt1235187,en,Where Hands Touch,...,2018-09-14,128269,122,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,웨어 핸즈 터치,False,8.1,400
26,False,/dbXjTu5J00kCggPnQlDpVZmDBil.jpg,None,12820005,"[{'id': 28, 'name': '액션'}, {'id': 18, 'name': ...",,437068,tt6878038,ko,택시운전사,...,2017-08-02,81927980,137,"[{'english_name': 'Korean', 'iso_639_1': 'ko',...",Released,"1980년 5월, 광주로 간 택시운전사",택시운전사,False,8.1,582
27,False,/pSjGsbqyKUzF8rHzL0vtVWV1pS6.jpg,None,0,"[{'id': 18, 'name': '드라마'}, {'id': 36, 'name':...",http://www.prayersforbobby.com,21634,tt1073510,en,Prayers for Bobby,...,2009-01-24,0,90,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,바비를 위한 기도,False,8.1,422
28,False,None,None,0,"[{'id': 35, 'name': '코미디'}]",,38288,tt3444066,it,I corti,...,1996-01-01,0,120,"[{'english_name': 'Italian', 'iso_639_1': 'it'...",Released,,I corti,False,8.1,318
29,False,/f0rEqxtjwBhQDOkOdk2t5UQmrFO.jpg,None,0,"[{'id': 10751, 'name': '가족'}, {'id': 10749, 'n...",http://www.achtstegroepersdefilm.nl/,115929,tt1800372,nl,Achtste Groepers Huilen Niet,...,2012-02-15,0,105,"[{'english_name': 'Dutch', 'iso_639_1': 'nl', ...",Released,,Achtste Groepers Huilen Niet,False,8.1,211
30,False,/e9mVA70m3vV8AYboOvJiXxJc2sQ.jpg,None,0,"[{'id': 18, 'name': '드라마'}, {'id': 10749, 'nam...",,42229,tt0076085,it,Una giornata particolare,...,1977-08-11,0,106,"[{'english_name': 'Italian', 'iso_639_1': 'it'...",Released,,특별한 날,False,8.1,479
31,False,/acqlcQWYE2F1ZRfS9dd4Mwb6BIO.jpg,None,4172781,"[{'id': 18, 'name': '드라마'}, {'id': 10752, 'nam...",http://aylafilmi.com/,472454,tt6316138,tr,Ayla,...,2017-10-27,0,125,"[{'english_name': 'Mandarin', 'iso_639_1': 'zh...",Released,"포화 속 생에 다시 없을 운명 같은 만남, 그리고··· 60년간의 그리움! 한국전쟁...",아일라,False,8.1,232
32,False,/l9w4vKgjStkoBxPYDGW2nYrtHai.jpg,None,0,"[{'id': 10751, 'name': '가족'}, {'id': 16, 'name...",,455661,tt6969946,en,In a Heartbeat,...,2017-06-01,0,4,"[{'english_name': 'No Language', 'iso_639_1': ...",Released,,인 어 하트비트,False,8.1,880

In [13]:
# 3. DB에 저장 ( "resource you requested could not be found."행 영화는 제거하고 필요한 컬럼만 가져온 후 저장)
import numpy as np
# 1. connect
conn = pymysql.connect(host="127.0.0.1", port=3306, db='finalteam3', user="kdigital", password="mysql", charset="utf8")

# 2. get command object
cursor = conn.cursor()

# cursor.execute("delete from movie") #기존 데이터를 지울 때 주석을 풀어주세요 

error_list = []   ##결과 18개
            
# movies2['original_language'] = movies2['original_language'].apply(lambda ol: ol if ol else '')
movies2['overview'] = movies2['overview'].apply(lambda ov : ov if str(ov) != 'nan' else '')
movies2['release_date'] = movies2['release_date'].apply(lambda ov : ov if str(ov) != 'nan' else '')
movies2['poster_path'] = movies2['poster_path'].apply(lambda ov : ov if str(ov) != 'nan' else '')
print(movies2.values.shape)
##결과: 630186 entries  ???????????????

# 3. execute command
sql = """insert into movie (movie_id, title, subtitle, original_language, overview, popularity, release_date, vote_average, vote_count, posterpath) 
        values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""
for movie in movies2.values:
    cursor.execute(sql, list(movie[list(np.array([9, 24, 12, 11, 13, 14, 18, 26, 27, 15]) - 3)]))

# movie3.append(list(movies2.values)) ##결과: 467108 entries    ????????????????????
                

conn.commit() # confirm previous execution
# 4. close resource
cursor.close()
conn.close()

(33, 25)

In [ ]:
"""  
import pymysql
import numpy as np

conn = pymysql.connect(host="localhost",
                       database="finalteam3",
                       user="kdigital",
                       password="mysql",
                       charset="utf8")
cursor = conn.cursor()

# cursor.execute('DELETE FROM top_rated_movies')

error_list = []
for movie in top_rated_movies.values:
    #print(movie_id)
    sql = "SELECT COUNT(*) FROM movie WHERE movie_id = %s"  # movie_id가 동일한 영화 정보가져오기
    cursor.execute(sql, movie[0])
    cnt = cursor.fetchone()
    print(cnt[0])    #0은 movie table에 없는 영화, 1은 있는 영화
    if cnt[0] == 0: # not exist
        sql = "insert into movie (movie_id, title, subtitle, original_language, overview, popularity, release_date, vote_average, vote_count, posterpath) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        cursor.execute(sql, list(movie[list(np.array([9, 24, 12, 11, 13, 14, 18, 26, 27, 15]))]))
    # print(type(movie_id), movie_id)  # movie_id type이 nd.arrary임. 삽입시 1차원으로.
    #print(type(movie_id[0]), movie_id[0])
    #sql= "INSERT INTO top_rated_movies VALUES(%s)"
    #cursor.execute(sql, movie_id[0])
    
conn.commit()
cursor.close()
conn.close()

"""